workspace 'SampleApp.xcworkspace'
platform :ios, '11.0'

def kidoz_pod
    pod 'KidozSDK','9.1.1'
end

target 'SampleAppSwift' do
  use_frameworks!
  kidoz_pod
  project 'SampleAppSwift/SampleAppSwift.xcodeproj'
end

target 'SampleAppObjc' do
  use_frameworks!
  kidoz_pod
  project 'SampleAppObjc/SampleAppObjc.xcodeproj'
end

target 'CommonSampleApp' do
  use_frameworks!
  kidoz_pod
  project 'CommonSampleApp/CommonSampleApp.xcodeproj'
end
