workspace 'SampleApp.xcworkspace'
platform :ios, '16.0'

def kidoz_pod
    pod 'KidozSDK','9.2.0'
end

def kidoz_mediation_adapter
    kidoz_pod
    pod 'KidozIronSourceAdapter', '1.4.0'
end

def ironSource_pods
    pod 'IronSourceSDK','8.9.0.0'
end

target 'SampleAppSwift' do
  use_frameworks!
  kidoz_mediation_adapter
  ironSource_pods
  project 'SampleAppSwift/SampleAppSwift.xcodeproj'
end

target 'SampleAppObjc' do
  use_frameworks!
  kidoz_mediation_adapter
  ironSource_pods
  project 'SampleAppObjc/SampleAppObjc.xcodeproj'
end

target 'CommonSampleApp' do
  use_frameworks!
  kidoz_pod
  project 'CommonSampleApp/CommonSampleApp.xcodeproj'
end
